POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhaW4iLCJpZCI6IjYwYjNmOGNiMWM4ZTBiMGRlNGFjODViOCIsImlhdCI6MTYzNjQ5NTkzNH0.85d4V19PsuFuoRNpT8PMadOEgaUO4w9W_x7403S2Gus

{
"title": "Comments are cool 1",
"author": "Max Pain",
"url": "www.terveystalo.fi",
"likes": 1
}
